### ISSUE TITLE
Multiple errors when trying to execute planar_piston_2d.py

### ISSUE THREAD

**Issue by Tomaubier** [samuelpgroth/waves-fenicsx#2]
Hi,
I've stumbled across a few errors when trying to run the `planar_piston_2d.py`demo.
For starters, the mesh attribute `hmin()` doesn't seem to exist anymore, I thus got
```AttributeError: 'dolfinx.cpp.mesh.Mesh' object has no attribute 'hmin'```
at line 226
```hmin = min(MPI.COMM_WORLD.allgather(mesh.hmin()))```
however I think I've been able to find a temporary workaround:
```
tdim = mesh.topology.dim
num_cells = mesh.topology.index_map(tdim).size_local
h = dolfinx.cpp.mesh.h(mesh, tdim, range(num_cells))
hmin = dolfinx.cpp.mesh.h(mesh, tdim, range(num_cells)).min()
```

After that I got
`ArityMismatch: Failure to conjugate test function in complex Form`
when trying to create the model
```
# Create model line 237
eqn = WesterveltEquation(mesh, k=degree, omega=omega, c=c0, wx=wx, wy=wy, amp=amp)
```
I haven't been able to fix that one yet. Do you have any clue regarding what's going on there?

**Comment by adeebkor** [comment]
Hi,

Are you running the code using the complex mode? If you are, you can change it to the real mode and the code will run. The command is

`source /usr/local/bin/dolfinx-real-mode`

**Comment by Tomaubier** [comment]
Yes, I made sure to execute `source /usr/local/bin/dolfinx-complex-mode` and checked it using `has_petsc_complex` from `dolfinx`
```
if has_petsc_complex:
    print('PETSc-complex is working correctly')
else:
    print('This demo only works with PETSc-complex')
```
In addition, the demo `demo0_scattering_by_circle.py`is working flawlessly in the same docker container.

**Comment by adeebkor** [comment]
The codes in the `/time` folder uses real mode instead of complex mode. Hence, you need to activate the real-mode of dolfinx.

**Comment by Tomaubier** [comment]
Ok, I'm sorry I didn't pay much attention there.. I will try this way thanks!
