### ISSUE TITLE
Update code for dolfinx:latest

### ISSUE THREAD

**Issue by pescap** [samuelpgroth/waves-fenicsx#3]
Hi, do you plan to refresh the code to adapt it to the last version of dolfinx? 
I made some progress/changes to run the frequency scripts with the current version.
Best wishes,
Paul

**Comment by adeebkor** [comment]
Hi Paul,

**Comment by adeebkor** [comment]
Hi Paul,

I've updated the frequency codes to work with the latest dolfinx. Hope this helps. 

Adeeb

**Comment by pescap** [comment]
Hi Adeeb, thank you for you help. Everything is working fine now! 🥇
